name: Linting

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0
    - name: Prettier
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.md
        dry: true
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install gitlint
      run: |
        python -m pip install --upgrade pip
        pip install gitlint
    - name: Run gitlint
      run: gitlint --commits "origin/master..HEAD"	
